version: '3.8'

services:
  # Monolith Service
  monolith:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/config.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Auth Service
  auth_service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      
  chat_service:
    build: ./chat-service
    ports:
      - "3002:3002"
    env_file:
      - ./chat-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  api_gateway:
    image: nginx:latest
    ports:
      - "8080:80" # Expose the gateway on host port 8080
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro # Mount config file
    depends_on:
      - monolith
      - auth_service
      - chat_service

  
  # RabbitMQ Event Bus Service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5